tarantool: fix Converter.updateNodeImpl()
This commit fixes the following error:

```
ERROR 2019-01-15 18:43:28,673 [Thread-0]: updateNode failed! org.tarantool.TarantoolException: Tuple field 5 type does not match one required by operation: expected string
ERROR 2019-01-15 18:43:28,674 [Thread-0]: UPDATE_NODE error Tuple field 5 type does not match one required by operation: expected string
org.tarantool.TarantoolException: Tuple field 5 type does not match one required by operation: expected string
        at org.tarantool.TarantoolClientImpl.serverError(TarantoolClientImpl.java:403)
        at org.tarantool.TarantoolClientImpl.complete(TarantoolClientImpl.java:416)
        at org.tarantool.TarantoolClientImpl.readThread(TarantoolClientImpl.java:347)
        at org.tarantool.TarantoolClientImpl$2.run(TarantoolClientImpl.java:163)
        at java.lang.Thread.run(Thread.java:748)
```

Converter.NodeToList() forms a tuple (a list) [0, type, version, time,
data], where 0 is a kind of placeholder for id.
Converter.updateNodeImpl() did send [id, 0, type, version, time, date]
before this commit, now it correctly sends [id, type, version, time,
date].